### ISSUE TITLE
Unable to use quick_tracker app in a venv

### ISSUE THREAD

**Issue by silverbucket** [QUIC-Tracker/web-app#1]
Trying to set up the web app to operate within a venv. However when I run pip3 (same binary) within the venv it is unable to find the dissector package.

```
quic-tracker# venv/bin/pip3 install quic-tracker-dissector
Collecting quic-tracker-dissector
Exception:
Traceback (most recent call last):
  File "/home/quic-tracker/venv/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/quic-tracker/venv/lib/python3.6/site-packages/pip/commands/install.py", line 353, in run
    wb.build(autobuilding=True)
  File "/home/quic-tracker/venv/lib/python3.6/site-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/home/quic-tracker/venv/lib/python3.6/site-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/home/quic-tracker/venv/lib/python3.6/site-packages/pip/req/req_set.py", line 554, in _prepare_file
    require_hashes
  File "/home/quic-tracker/venv/lib/python3.6/site-packages/pip/req/req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/home/quic-tracker/venv/lib/python3.6/site-packages/pip/index.py", line 465, in find_requirement
    all_candidates = self.find_all_candidates(req.name)
  File "/home/quic-tracker/venv/lib/python3.6/site-packages/pip/index.py", line 423, in find_all_candidates
    for page in self._get_pages(url_locations, project_name):
  File "/home/quic-tracker/venv/lib/python3.6/site-packages/pip/index.py", line 568, in _get_pages
    page = self._get_page(location)
  File "/home/quic-tracker/venv/lib/python3.6/site-packages/pip/index.py", line 683, in _get_page
    return HTMLPage.get_page(link, session=self.session)
  File "/home/quic-tracker/venv/lib/python3.6/site-packages/pip/index.py", line 795, in get_page
    resp.raise_for_status()
  File "/home/quic-tracker/venv/share/python-wheels/requests-2.18.4-py2.py3-none-any.whl/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://pypi.org/simple/quic-tracker-dissector/
```

When I run it outside the venv, it works:
```
# pip3 install .
Processing /home/quic-tracker
  Requirement already satisfied (use --upgrade to upgrade): quic-tracker==0.1 from file:///home/quic-tracker in /usr/local/lib/python3.6/dist-packages
Requirement already satisfied: PyYAML in /usr/local/lib/python3.6/dist-packages (from quic-tracker==0.1)
Requirement already satisfied: flask in /usr/local/lib/python3.6/dist-packages (from quic-tracker==0.1)
Requirement already satisfied: quic-tracker-dissector in /usr/local/lib/python3.6/dist-packages (from quic-tracker==0.1)
Requirement already satisfied: click>=5.1 in /usr/local/lib/python3.6/dist-packages (from flask->quic-tracker==0.1)
Requirement already satisfied: itsdangerous>=0.24 in /usr/local/lib/python3.6/dist-packages (from flask->quic-tracker==0.1)
Requirement already satisfied: Werkzeug>=0.15 in /usr/local/lib/python3.6/dist-packages (from flask->quic-tracker==0.1)
Requirement already satisfied: Jinja2>=2.10.1 in /usr/local/lib/python3.6/dist-packages (from flask->quic-tracker==0.1)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib/python3.6/dist-packages (from Jinja2>=2.10.1->flask->quic-tracker==0.1)
Building wheels for collected packages: quic-tracker
  Running setup.py bdist_wheel for quic-tracker ... done
  Stored in directory: /root/.cache/pip/wheels/73/6b/65/c996a9a3c26c3eb77bab3880dcd074a8adda09deb4439b8d52
Successfully built quic-tracker
```

(Note: I manually added `pyyaml` as a dependency in setup.py)

When I check pypi.org `quic-tracker-dissector` does not show up at all.

**Comment by mpiraux** [comment]
Hi,
You probably want to use `venv/bin/pip3 install --upgrade git+https://github.com/QUIC-Tracker/dissector git+https://github.com/QUIC-Tracker/web-app`. No packages are published on pypi yet.
